### PR TITLE
Migrate to pure async functions and bring back non-host-object API

### PR DESCRIPTION
**Pull request by ospfranco**

### CODE REVIEW

**Comment by rvibit** [comment]
@ospfranco so in new version we'll not have sync API, just like we have now?

**Comment by ospfranco** [comment]
No, it's too much work to keep both in sync

**Comment by rvibit** [comment]
> No, it's too much work to keep both in sync

Oh ok, i like sync api more but can't do anything now 😅

**Comment by ospfranco** [comment]
sync API is in almost all cases the wrong API to **use**. It's easier to use but except for the most simplest of queries brings no other value than DX.

**Comment by rvibit** [comment]
> sync API is in almost all cases the wrong API to **use**. It's easier to use but except for the most simplest of queries brings no other value than DX.

Ah ok got it

**Comment by omniphx** [comment]
@ospfranco will this change restore the use of the [spread operator](https://github.com/OP-Engineering/op-sqlite/issues/130)?

**Comment by ospfranco** [comment]
Yes

**Comment by patlux** [comment]
That's really sad...time to move to expo-sqlite for the sync api

**Pull request merged**
