### PR TITLE
Support crsqlite for libsql

### PR DESCRIPTION
**Pull request by haaawk**

### CODE REVIEW

**Comment by haaawk** [comment]
I'm trying to test this but when running `yarn ios` I get an error despite setting `export NODE_BINARY=$(command -v node)`:

```
The following build commands failed:
	PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/haaawk/Library/Developer/Xcode/DerivedData/OPSQLiteExample-gactwnlhcoacyfdfxuiffpwqkjjz/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E00012FF0.sh (in target 'hermes-engine' from project 'Pods')
(1 failure)
]

Node.js v18.17.0
```

**Comment by ospfranco** [comment]
For iOS, you need to get more output on the error. If you open Xcode go to the `build` tab on the right hand panel, then look for the most recent build and scroll until you find the error output:



For Android, the recent builds of the emulator broke the CLI tools by outputting an error message when running commands. You need to run the emulator yourself first then the build scripts will work. I use [minisim](https://www.minisim.app/) to quickly launch the emulator first.

**Comment by ospfranco** [comment]
I forgot to write, but you also need to update the header on `cpp/libsql/libsql.h`. After doing that, I'm getting the following error:

OSP 000149
OSP 000150

Seems the header definition is missing a `const` declaration.

**Comment by ospfranco** [comment]
I've committed the updated libsql.h.

Did you do a `pod install` on `example/ios`?

**Comment by haaawk** [comment]
> I've committed the updated libsql.h.
> 
> Did you do a `pod install` on `example/ios`?

I did not. I was following https://ospfranco.notion.site/Libsql-4dbbf5793f654eccb9f5f68901224e97

**Comment by ospfranco** [comment]
yarn pods is the same, it just runs the command on the package.json, but either bundle exec pod install or just pod install mean "install the pods"

**Comment by haaawk** [comment]
> yarn pods is the same, it just runs the command on the package.json, but either bundle exec pod install or just pod install mean "install the pods"

I did run yarn pods and it finished succesfully

**Comment by ospfranco** [comment]
OSP 000151

**Comment by ospfranco** [comment]
I have to go for some hours. Send me a message on Discord, let's debug your environment so you have running simulators. I have also updated the notion doc, whenever the headers are changed.

**Comment by haaawk** [comment]
> OSP 000151

It seem that `crsqlitePath` might be empty

**Comment by haaawk** [comment]
image

**Comment by ospfranco** [comment]
Android?

**Comment by haaawk** [comment]
> Android? :)

Still fighting that :)

**Comment by haaawk** [comment]
image

**Pull request merged**
