### PR TITLE
update libsql library

### PR DESCRIPTION
**Pull request by haaawk**
Update libsql library to https://github.com/tursodatabase/libsql/commit/5d2501817056e186822ba29644717ef056519643

### CODE REVIEW

**Comment by haaawk** [comment]
Trying to run tests but yarn install does not seem to work any more:
```
╰──> yarn install
yarn install v1.22.19
error Workspaces can only be enabled in private projects.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ospfranco** [comment]
Seems unlikely, are you sure you are running yarn install in the correct folder? Nothing changed since your PR a couple of days ago.

**Comment by ospfranco** [comment]
OSP 000216

Checked out the PR, yarn install works on root and Example.

**Comment by haaawk** [comment]
I tried both in repo root and in example dir. Both fail with this error

**Comment by haaawk** [comment]
Ok I figured it out. It was wrong version of node.

**Comment by ospfranco** [comment]
Cool, I assume the tests are running, I will just go ahead and merge it.

**Comment by haaawk** [comment]
image

**Comment by haaawk** [comment]
image

**Comment by haaawk** [comment]
Thanks @ospfranco

**Comment by Volland** [comment]
@ospfranco could we get a release version ?

**Comment by ospfranco** [comment]
already released in the latest version

**Comment by ospfranco** [comment]
7.3.0 is already out. You can just hover on vscode on the dependency number and it will show you the latest package version

**Pull request merged**
