### PR TITLE
Update libsql to 3d52c07f5d1df9caa56fb201fb3009924b26fd05

### PR DESCRIPTION
**Pull request by haaawk**
It includes some fixes to vector search.

### CODE REVIEW

**Comment by haaawk** [comment]
Updating simulator to IOS 18.1 helped:
image

**Comment by ospfranco** [comment]
It seems you didn't do a `pod install`? I'm getting changes on the Podfile.lock:

CleanShot 2024-11-26 at 14 23 53@2x

**Comment by ospfranco** [comment]
I fixed the CI command, you can merge main into your branch or rebase if you want, should fix the CI tests at least

**Comment by haaawk** [comment]
> It seems you didn't do a `pod install`? I'm getting changes on the Podfile.lock:
> 
> CleanShot 2024-11-26 at 14 23 53@2x

I did - just didn't commit Podfile.lock

**Comment by haaawk** [comment]
Rebased on main

**Comment by ospfranco** [comment]
Thanks, release `11.0.1` is now building and will contain this bump.

**Comment by haaawk** [comment]
> Thanks, release `11.0.1` is now building and will contain this bump.

Thanks @ospfranco !!!

**Comment by simonwh** [comment]
Thanks guys! @ospfranco - can you push 11.0.1 to npm?

**Comment by ospfranco** [comment]
It's already out

https://github.com/OP-Engineering/op-sqlite/releases/tag/11.0.1

**Comment by simonwh** [comment]
@ospfranco it's not pushed to npm https://www.npmjs.com/package/@op-engineering/op-sqlite?activeTab=versions

**Pull request merged**
