### PR TITLE
Update libsql library

### PR DESCRIPTION
**Pull request by haaawk**

### CODE REVIEW

**Comment by haaawk** [comment]
For some reason the example does not pick up any tests:
Screenshot 2024-08-15 at 12 59 25
Screenshot 2024-08-15 at 13 13 12

**Comment by ospfranco** [comment]
It means the tests are not completing.

**Comment by haaawk** [comment]
> It means the tests are not completing.

But they are green not red so they are not failing either, right?

**Comment by ospfranco** [comment]
They are failing alright, they are not halting/completing correctly, an infinite loop somewhere maybe?

**Comment by ospfranco** [comment]
If I comment the replicated turso db tests then it works fine. I guess the functions are not failing properly when the turso database group is put to sleep or something similar?

OSP 000211

**Comment by haaawk** [comment]
> If I comment the replicated turso db tests then it works fine. I guess the functions are not failing properly when the turso database group is put to sleep or something similar?
> 
> OSP 000211

Let me try to use my own db

**Comment by haaawk** [comment]
When I updated the token and db url all tests but 1 pass. The failed one is just complaining that libsql is using newer sqlite version.

Screenshot 2024-08-15 at 17 52 36
Screenshot 2024-08-15 at 17 54 05

**Comment by ospfranco** [comment]
Well, seems like you bumped the internall sqlite version? So you need to update the test.

Also, a non returning call if the db is not working is the wrong behavior. The function should return an error correctly. So you probably want to add a test for it and make sure it is working correctly.

**Comment by haaawk** [comment]
Updated the expected libsql version - now all the tests are passing

**Comment by ospfranco** [comment]
You don't want to check why the functions are not returning when connection is failing?

**Comment by haaawk** [comment]
I actually checked it yesterday. It seems that the timeout is wrongly setup
image

**Comment by haaawk** [comment]
I'm taking a closer look at it

**Comment by haaawk** [comment]
The delay comes from sync call. This makes the tests run instantly. I will investigate why.

```
diff --git a/example/src/tests/queries.spec.ts b/example/src/tests/queries.spec.ts
index 95c1c92..591b702 100644
--- a/example/src/tests/queries.spec.ts
+++ b/example/src/tests/queries.spec.ts
@@ -61,7 +61,7 @@ export function queriesTests() {
 
         const res = remoteDb.execute('SELECT 1');
 
-        remoteDb.sync();
+        //remoteDb.sync();
 
         expect(res.rowsAffected).to.equal(0);
       });
```

**Comment by haaawk** [comment]
This is not a regression. It seems that we have timeouts miscofigured in sync. I filled an issue so that we can fix this for the next update -> https://github.com/tursodatabase/libsql/issues/1676

**Comment by ospfranco** [comment]
Alright, will release it

**Comment by ospfranco** [comment]
Building in `7.2.0`

**Comment by haaawk** [comment]
Thanks @ospfranco

**Pull request merged**
